# Generated by Django 4.2 on 2023-05-24 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attrazioni',
            name='label',
        ),
        migrations.AddField(
            model_name='attrazioni',
            name='labels',
            field=models.ManyToManyField(to='main.label'),
        ),
    ]
