# Generated by Django 4.0.6 on 2023-07-12 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_services_label_remove_story_label_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Label',
        ),
    ]
