# Generated by Django 4.2.5 on 2023-10-05 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('story', '0019_ipmodel_story_views'),
        ('main', '0004_delete_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views', models.ManyToManyField(blank=True, default=0, related_name='main_views', to='story.ipmodel')),
            ],
        ),
    ]
