# Generated by Django 4.0.6 on 2023-07-05 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attraction', '0002_attraction_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopAttraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attraction.attraction')),
            ],
        ),
    ]
