# Generated by Django 4.2.5 on 2023-09-27 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attraction', '0005_topattraction_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=255, null=True, unique=True),
        ),
    ]
