# Generated by Django 4.2.5 on 2023-10-05 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attraction', '0008_attraction_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='top',
            field=models.BooleanField(default=False),
        ),
    ]
