# Generated by Django 4.2 on 2023-07-01 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunication',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
