# Generated by Django 4.2.5 on 2023-10-05 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0002_comunication_slug'),
        ('communication', '0003_comunication_available'),
    ]

    operations = [
    ]
