# Generated by Django 4.2 on 2023-07-01 18:57

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
