# Generated by Django 4.0.6 on 2023-07-12 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='service',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
