# Generated by Django 4.2.5 on 2023-10-05 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_category_slug_service_slug'),
        ('services', '0003_category_available_service_available'),
    ]

    operations = [
    ]
