# Generated by Django 4.2.5 on 2023-09-26 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='available',
        ),
        migrations.RemoveField(
            model_name='story',
            name='body',
        ),
        migrations.RemoveField(
            model_name='story',
            name='fonti',
        ),
        migrations.RemoveField(
            model_name='story',
            name='iframe',
        ),
        migrations.RemoveField(
            model_name='story',
            name='img',
        ),
        migrations.RemoveField(
            model_name='story',
            name='intro',
        ),
        migrations.RemoveField(
            model_name='story',
            name='name',
        ),
        migrations.RemoveField(
            model_name='story',
            name='outline',
        ),
    ]
