# Generated by Django 4.2.5 on 2023-09-26 21:43

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0002_remove_story_available_remove_story_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='story',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='fonti',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='iframe',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='story',
            name='intro',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='outline',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
