# Generated by Django 4.2 on 2023-07-01 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0002_remove_story_body_story_slug_image_didascalia'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='intro',
            field=models.TextField(default='intro'),
        ),
        migrations.AddField(
            model_name='story',
            name='intro_title',
            field=models.CharField(default='intro_title', max_length=255),
        ),
    ]
