# Generated by Django 4.2.5 on 2023-09-26 21:44

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('story', '0003_story_available_story_body_story_fonti_story_iframe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='tag',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
