# Generated by Django 4.2 on 2023-07-01 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0004_citazione_story_body_story_cit_story_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='img',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
