# Generated by Django 4.2 on 2023-07-01 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0005_story_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='story',
            name='img',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
