# Generated by Django 4.2.5 on 2023-09-27 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0005_alter_story_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='slug',
            field=models.SlugField(default='djangodbmodelsfieldscharfield', max_length=255, unique=True),
        ),
    ]
