# Generated by Django 4.2 on 2023-07-01 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0007_alter_story_cit_alter_story_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='iframe',
            field=models.URLField(null=True),
        ),
    ]
