# Generated by Django 4.2 on 2023-07-01 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0008_story_iframe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='iframe',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
