# Generated by Django 4.2 on 2023-07-04 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0009_alter_story_iframe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='cit',
        ),
        migrations.RemoveField(
            model_name='story',
            name='description',
        ),
        migrations.RemoveField(
            model_name='story',
            name='didascalia_cit',
        ),
        migrations.RemoveField(
            model_name='story',
            name='intro',
        ),
        migrations.RemoveField(
            model_name='story',
            name='intro_title',
        ),
        migrations.RemoveField(
            model_name='story',
            name='slug',
        ),
    ]
