# Generated by Django 4.2.5 on 2023-09-27 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0009_alter_story_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
