# Generated by Django 4.2 on 2023-07-04 16:14

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0011_alter_story_iframe_alter_story_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='intro',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
