# Generated by Django 4.2.5 on 2023-09-27 09:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('story', '0012_story_date_story_liked_like'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Like',
            new_name='LikeStory',
        ),
    ]
