# Generated by Django 4.0.6 on 2023-07-05 10:08

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0012_story_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='fonti',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='outline',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
