# Generated by Django 4.0.6 on 2023-07-12 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0014_topstories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='story',
        ),
        migrations.AddField(
            model_name='story',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='Citazione',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
