# Generated by Django 4.2.5 on 2023-10-05 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0013_rename_like_likestory'),
        ('story', '0017_alter_story_img'),
    ]

    operations = [
    ]
