# Generated by Django 4.2.5 on 2023-10-05 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0018_merge_0013_rename_like_likestory_0017_alter_story_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='story',
            name='views',
            field=models.ManyToManyField(blank=True, default=0, related_name='post_views', to='story.ipmodel'),
        ),
    ]
