# Generated by Django 4.2.5 on 2023-10-05 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0020_alter_story_intro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='views',
            field=models.ManyToManyField(blank=True, default=0, editable=False, related_name='post_views', to='story.ipmodel'),
        ),
    ]
