# Generated by Django 4.2.5 on 2023-10-05 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0021_alter_story_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='top',
            field=models.BooleanField(default=False),
        ),
    ]
